### ISSUE TITLE
getting error when destroying my first block and whole game gets stuck

### ISSUE THREAD

**Issue by levlups** [sciner/webcraft#77]
Uncaught TypeError: lastBuffer.destroy is not a function
    at TrivialGeometryPool.alloc (GeometryPool.js:28:24)
    at Chunk.applyVertices (chunk.js:262:65)
    at ChunkManager.prepareRenderList (chunk_manager.js:282:27)
    at Renderer.update (render.js:516:12)
    at GameClass.loop (game.js:477:25)

**Comment by levlups** [comment]
was not using main branch , thats why it was working

**Comment by ivanpopelyshev** [comment]
its my `dev-chunk-batch` branch, im trying to use multidraw extension https://www.khronos.org/registry/webgl/extensions/WEBGL_multi_draw_instanced_base_vertex_base_instance/

So far its slow as heck.
